GET http://localhost:4000/users

##########
POST http://localhost:4000/users
Content-Type: application/json

{
    "username": "dodo",
    "password": "22222"
}

##########
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "username": "dodo",
    "password": "22222"
}

##########
POST http://localhost:4000/users/posts
Content-Type: application/json
